version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-api-cache
    command: redis-server --requirepass 1234
    environment:
      - REDIS_PASSWORD=1234
    ports:
      - "6379:6379"
